local Forgeframe = CreateFrame("Frame")
Forgeframe:RegisterEvent("PLAYER_LOGIN")
Forgeframe:SetScript("OnEvent", function()
    --InitializeTalentTree()
    initializeItemTooltips()
    InitializePerks(false)
    initializeAllStats()
    InitializeTransmog()
    InitInstance()
    InitWorldTierSelect()
    InitializeSoulShardWindow()
    InitPortalmasterSelect()
end)
